export const CLI_NAME = 'trace-cue';
export const PACKAGE_VERSION = '0.0.0';
export const SCHEMA_VERSION = '0.1.0';
export const MIN_NODE_MAJOR = 20;
export const DEFAULT_ARTIFACT_ROOT = '.browser-debug';

export const SCHEMA_VERSION_POLICY = Object.freeze({
  current: SCHEMA_VERSION,
  stage: 'mvp-pre-1.0',
  compatible_change: 'additive fields may be added while existing fields keep their meaning and type',
  breaking_change: 'rename, removal, or type changes require a schema version bump'
});

export const ARTIFACT_RETENTION_POLICY = Object.freeze({
  mode: 'manual',
  automatic_cleanup: false,
  cleanup_command: 'trace-cue resource artifacts cleanup --execute',
  default_root: DEFAULT_ARTIFACT_ROOT
});

export const PLANNED_COMMANDS = Object.freeze([
  'doctor',
  'observe',
  'supervise',
  'daemon start',
  'daemon status',
  'daemon stop',
  'resource status',
  'resource artifacts plan',
  'resource artifacts cleanup',
  'control-center status',
  'control-center serve',
  'control-center launch',
  'agent surfaces list',
  'agent requests list',
  'agent requests show',
  'agent workflow create',
  'agent workflow status',
  'agent workflow index',
  'agent workflow report',
  'agent execution plan',
  'agent execution run',
  'agent execution status',
  'agent execution list',
  'agentic review propose',
  'agentic review plan',
  'agentic review run',
  'agentic review status',
  'agentic review list',
  'agentic review provider-readiness',
  'agentic review report-quality',
  'agentic review benchmark list',
  'agentic review benchmark show',
  'agentic review dogfood readiness',
  'agentic review dogfood plan',
  'agentic review calibrate',
  'agentic review compare',
  'agentic review evidence-set regenerate plan',
  'agentic review quality source-text',
  'visual review plan',
  'visual review prepare',
  'visual review run',
  'visual review status',
  'visual review list',
  'visual review dashboard',
  'playwright-test mode',
  'playwright-test status',
  'playwright-test list',
  'playwright-test report',
  'playwright-test import',
  'playwright-test local plan',
  'playwright-test local run',
  'playwright-test external-ci readiness',
  'playwright-test external-ci list',
  'playwright-test external-ci view',
  'playwright-test external-ci fetch',
  'playwright-test external-ci approved-settings',
  'playwright-test external-ci suggest-settings',
  'playwright-test external-ci approve-settings',
  'playwright-test external-ci resolve-approved',
  'playwright-test external-ci fetch-approved',
  'identity audit',
  'identity aliases',
  'identity aliases removal-readiness',
  'identity aliases remove',
  'artifact-root status',
  'artifact-root migration plan',
  'artifact-root migration execute',
  'release readiness',
  'shell readiness',
  'shell plan',
  'shell run',
  'final readiness',
  'capture plan',
  'media source inspect',
  'media review readiness',
  'media review plan',
  'media review run',
  'media review cleanup',
  'capture handoff',
  'settings show',
  'settings language',
  'settings language policy',
  'agent package',
  'agent ingest',
  'agent report',
  'target init',
  'target validate',
  'session start',
  'session status',
  'session stop',
  'session close',
  'session act',
  'session observe',
  'session checkpoint',
  'session review',
  'act',
  'report',
  'spec export',
  'review',
  'schema list',
  'schema get',
  'mcp serve',
  'mcp config',
  'mcp capabilities',
  'mcp execution gates',
  'operation registry',
  'operation roadmap',
  'operation contracts',
  'operation policy',
  'operation admin-readiness',
  'operation provider-readiness'
]);
